# Generated by Django 2.1.3 on 2018-12-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('contract_number', models.CharField(max_length=10)),
                ('date_conclusion', models.DateField()),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('permissions', models.CharField(max_length=30)),
            ],
        ),
    ]
